
name: mundo_origami
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  flutter_hooks: ^0.21.2
  provider: ^6.1.1
  hooks_riverpod: ^2.4.0
  font_awesome_flutter: ^10.6.0
  carousel_slider: ^5.0.0
  youtube_player_flutter: ^9.1.1 
  http: ^1.1.0
  youtube_player_iframe: ^5.2.1
  cloud_firestore: ^5.6.7
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  flutter_cube: ^0.1.1
  path_provider: ^2.0.15
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.3
  url_launcher: ^6.2.0
  flutter_staggered_grid_view: ^0.7.0

 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/logo.png
    - assets/images/avatars/avatar_1.png
    - assets/images/avatars/avatar_2.png
    - assets/images/avatars/avatar_3.png
    - assets/images/avatars/avatar_4.png
    - assets/images/avatars/avatar_5.png
    - assets/images/avatars/avatar_6.png
    - assets/images/avatars/avatar_7.png
    - assets/images/avatars/avatar_8.png
    - assets/images/avatars/avatar_9.png
    - assets/images/avatars/avatar_10.png
    - assets/images/avatars/avatar_11.png
    - assets/images/avatars/avatar_12.png
    - assets/images/avatars/avatar_13.png
    - assets/images/avatars/avatar_14.png
    - assets/images/avatars/avatar_15.png
    - assets/images/avatars/avatar_16.png
    - assets/images/avatars/avatar_17.png
    - assets/images/avatars/avatar_18.png
    - assets/images/avatars/avatar_19.png
    - assets/images/avatars/avatar_20.png
    - assets/images/avatars/avatar_21.png
    - assets/images/avatars/avatar_22.png
    - assets/images/avatars/avatar_23.png
    - assets/images/avatars/avatar_24.png
    - assets/images/avatars/avatar_25.png
    - assets/images/avatars/avatar_26.png
    - assets/images/avatars/avatar_27.png
    - assets/images/avatars/avatar_28.png
    - assets/images/avatars/avatar_29.png
    - assets/images/avatars/avatar_30.png

    

    - assets/images/avatars/especiales/a_1.png
    - assets/images/avatars/especiales/a_2.png
    - assets/images/avatars/especiales/a_3.png
    - assets/images/avatars/especiales/a_4.png
    - assets/images/avatars/especiales/a_5.png
    - assets/images/avatars/especiales/a_6.png
    - assets/images/avatars/especiales/a_7.png
    - assets/images/avatars/especiales/a_8.png
    - assets/images/avatars/especiales/a_9.png
    - assets/images/avatars/especiales/a_10.png
    - assets/images/avatars/especiales/a_11.png
    - assets/images/avatars/especiales/a_12.png
    - assets/images/avatars/especiales/a_13.png
    - assets/images/avatars/especiales/a_14.png
    - assets/images/avatars/especiales/a_15.png
    - assets/images/avatars/especiales/a_16.png
    - assets/images/avatars/especiales/a_17.png
    - assets/images/avatars/especiales/a_18.png
    - assets/images/avatars/especiales/a_19.png
    - assets/images/avatars/especiales/a_20.png
    - assets/images/avatars/especiales/a_21.png
    - assets/images/avatars/especiales/a_22.png
    - assets/images/avatars/especiales/a_23.png
    - assets/images/avatars/especiales/a_24.png
    - assets/images/avatars/especiales/a_25.png
    - assets/images/avatars/especiales/a_26.png
    - assets/images/avatars/especiales/a_27.png
    - assets/images/avatars/especiales/a_28.png
    - assets/images/avatars/especiales/a_29.png
    - assets/images/avatars/especiales/a_30.png
    - assets/images/avatars/especiales/a_31.png
    - assets/images/avatars/especiales/a_32.png
    - assets/images/avatars/especiales/a_33.png
    - assets/images/avatars/especiales/a_34.png
    - assets/images/avatars/especiales/a_35.png
    - assets/images/avatars/especiales/a_36.png
    - assets/images/avatars/especiales/a_37.png

    - assets/images/origami_bg.jpg
    - assets/images/comparte.jpg
    - assets/images/crea.jpg
    - assets/images/f2.jpg
    - assets/images/f3.jpg
    - assets/images/f4.png
    - assets/images/f5.jpg
    - assets/images/t.png
    - assets/images/tutorial.png
    - assets/images/x.png

    - assets/images/n.gif
    - assets/images/lol.gif
    - assets/images/vuela.gif

    

  fonts:

  
  - family: PoetsenOne
    fonts:
      - asset: assets/fonts/Origami.ttf


  - family: CocoGothic
    fonts:
      - asset: assets/fonts/Starbim.otf
  - family: Fors
    fonts:
      - asset: assets/fonts/Milky Juice.otf

  - family: OrigamiFont
    fonts:
      - asset: assets/fonts/x/PoetsenOne-Regular.ttf

  - family: Origame
    fonts:
      - asset: assets/fonts/origame.ttf
