// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfYVdGNX_zXQAJqhrNfVr5J6ramFBUoSI',
    appId: '1:333758494548:web:310e4b8031cf642631bac1',
    messagingSenderId: '333758494548',
    projectId: 'im4-dibujos',
    authDomain: 'im4-dibujos.firebaseapp.com',
    storageBucket: 'im4-dibujos.firebasestorage.app',
    measurementId: 'G-MHXRPK06P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIT65TccMBrFgOpRPdlMPJPp7FaGTYMVo',
    appId: '1:333758494548:android:72b1ed1b8ea6aeb231bac1',
    messagingSenderId: '333758494548',
    projectId: 'im4-dibujos',
    storageBucket: 'im4-dibujos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4x0s0eBqBqHUELbpNDcaxkRepuKH7qNY',
    appId: '1:333758494548:ios:cabf324c4dae65f631bac1',
    messagingSenderId: '333758494548',
    projectId: 'im4-dibujos',
    storageBucket: 'im4-dibujos.firebasestorage.app',
    iosBundleId: 'com.example.mundoOrigami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4x0s0eBqBqHUELbpNDcaxkRepuKH7qNY',
    appId: '1:333758494548:ios:cabf324c4dae65f631bac1',
    messagingSenderId: '333758494548',
    projectId: 'im4-dibujos',
    storageBucket: 'im4-dibujos.firebasestorage.app',
    iosBundleId: 'com.example.mundoOrigami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfYVdGNX_zXQAJqhrNfVr5J6ramFBUoSI',
    appId: '1:333758494548:web:310e4b8031cf642631bac1',
    messagingSenderId: '333758494548',
    projectId: 'im4-dibujos',
    authDomain: 'im4-dibujos.firebaseapp.com',
    storageBucket: 'im4-dibujos.firebasestorage.app',
    measurementId: 'G-MHXRPK06P4',
  );
}